// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class DicodingtestTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver","E:\\Aplikasi\\chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void dicodingTestSearchData() {
    driver.get("https://www.dicoding.com/");
    driver.manage().window().setSize(new Dimension(1936, 1056));
    driver.findElement(By.id("navbarDropdownMenuLink")).click();
    driver.findElement(By.id("navbarDropdownMenuLink")).click();
    driver.findElement(By.cssSelector(".gtm-study-now-btn")).click();
    js.executeScript("window.scrollTo(0,345)");
    driver.findElement(By.name("q")).click();
    driver.findElement(By.name("q")).sendKeys("web");
    driver.findElement(By.name("q")).sendKeys(Keys.ENTER);
    driver.findElement(By.cssSelector(".content-wrapper"));
  }
  @Test
  public void loginGithub() {
    driver.get("https://github.com/");
    driver.manage().window().setSize(new Dimension(1936, 1056));
    driver.findElement(By.linkText("Sign in")).click();
    driver.findElement(By.id("login_field")).sendKeys("Azizalfauzi");
    driver.findElement(By.id("password")).sendKeys("@kucintamega1");
    driver.findElement(By.id("login")).click();
    driver.findElement(By.id("js-pjax-container")).click();
    driver.findElement(By.id("password")).click();
    driver.findElement(By.name("commit")).click();
  }
  @Test
  public void dicodingTestChallengesPage() {
    driver.get("https://www.dicoding.com/");
    driver.manage().window().setSize(new Dimension(1936, 1056));
    driver.findElement(By.cssSelector("#dicoding-challenge strong")).click();
  }
  @Test
  public void dicodingTestOpenClassPage() {
    driver.get("https://www.dicoding.com/");
    driver.manage().window().setSize(new Dimension(1936, 1056));
    driver.findElement(By.cssSelector(".gtm-study-now-btn")).click();
    js.executeScript("window.scrollTo(0,776)");
    js.executeScript("window.scrollTo(0,2622)");
    driver.findElement(By.cssSelector(".col-sm-6:nth-child(25) .cta-to-detail .mb-0")).click();
  }
  @Test
  public void dicodingTestEventPage() {
    driver.get("https://www.dicoding.com/");
    driver.manage().window().setSize(new Dimension(1936, 1056));
    driver.findElement(By.cssSelector("#dicoding-event-tab .font-weight-600")).click();
    driver.findElement(By.cssSelector("#dicoding-event strong")).click();
    js.executeScript("window.scrollTo(0,13)");
  }
}
